import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

// Codegen: bundle the static GUI files into a plain TS module so a single-file
// executable (bun --compile) can serve them from memory — see build_doc/PLAN-release.md (R1).
// Run via `npm run embed:gui`; `prebuild` regenerates it before each exe build.
// The output is committed (a build-time cache) so a fresh checkout type-checks; the
// drift-guard test (tests/guiEmbed.test.ts) fails if src/gui changes without a re-run.

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const GUI_DIR = join(ROOT, "src", "gui");
const OUT = join(GUI_DIR, "embedded.generated.ts");
const FILES = ["index.html", "styles.css", "app.js"];

const entries = FILES.map((f) => `  ${JSON.stringify(f)}: ${JSON.stringify(readFileSync(join(GUI_DIR, f), "utf8"))},`).join("\n");

const out = `// GENERATED by scripts/embed-gui.ts — do not edit by hand.
// Run \`npm run embed:gui\` to regenerate after editing any src/gui/* file.

/** Static GUI files inlined at build time so the packaged executable can serve
 *  them without a src/gui/ directory on disk. */
export const EMBEDDED: Record<string, string> = {
${entries}
};
`;

writeFileSync(OUT, out);
console.log(`embedded ${FILES.length} gui file(s) → ${OUT}`);
